TIMEFRAMES = ('1m', '1d')
TIMEFRAME_1M = '1m'
TIMEFRAME_1D = '1d'

IBKR_HOST = '127.0.0.1'
IBKR_PORT = 7496
IBKR_CLIENT_ID = 1

TICK_BY_TICK_TYPE = 'AllLast'

MAX_BARS_MEMORY = 10_000
PERIODIC_REFRESH_INTERVAL = 1.0  # seconds

REGULAR_HOURS_START = 9.5  # 9:30 AM NY
REGULAR_HOURS_END = 16.0  # 4:00 PM NY

DEFAULT_TIMEFRAME = '1m'

CONFIG_PATH = 'config/config.yaml'
INDICATORS_CONFIG_PATH = 'config/indicators.yaml'

DEFAULT_CHART_VISIBLE_BARS = 240
